identifier_fb: ''
secret_fb: ''
identifier_tw: ''
secret_tw: ''
identifier_gg: '.apps.googleusercontent.com'
secret_gg: ''
identifier_gg_local: '763337293862-pcruu8kkagfvqq9868unua8go28clsg3.apps.googleusercontent.com'
secret_gg_local: 'R6yZ-Ldlu6DrJLa6ziD20b5i'